[tool.poetry]
name = "dimastbkbot"
version = "0.1.0"
description = ""
authors = ["dima_st_bk <dimastbk@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.5"
Flask = "^1.1"
Flask-Migrate = "^2.5"
Flask-SQLAlchemy = "^2.4"
PyMySQL = "^0.9.3"
python-dotenv = "^0.10.3"
pytest = "^5.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-isort = "^2.7"
flake8-print = "^3.1"
flake8-quotes = "^2.1"
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
