"""empty message

Revision ID: 03667a1c8139
Revises: 7df6e2728025
Create Date: 2021-11-13 22:44:28.849943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03667a1c8139"
down_revision = "7df6e2728025"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gkgn_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "create_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "update_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="Дата обновления",
        ),
        sa.Column("name", sa.String(length=255), nullable=True, comment="Тип"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gkgn_object",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "create_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "update_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="Дата обновления",
        ),
        sa.Column("gkgn_id", sa.String(length=8), nullable=True, comment="Код ГКГН"),
        sa.Column("name", sa.String(length=255), nullable=True, comment="Название"),
        sa.Column("type_id", sa.Integer(), nullable=True, comment="Тип"),
        sa.Column("level", sa.String(length=10), nullable=True, comment="Уровень"),
        sa.Column("lat", sa.Float(precision=6), nullable=True, comment="Широта"),
        sa.Column("lon", sa.Float(precision=6), nullable=True, comment="Долгота"),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["gkgn_object.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["gkgn_object.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["gkgn_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gkgn_object_district_id"), "gkgn_object", ["district_id"], unique=False
    )
    op.create_index(
        op.f("ix_gkgn_object_gkgn_id"), "gkgn_object", ["gkgn_id"], unique=False
    )
    op.create_index(
        op.f("ix_gkgn_object_level"), "gkgn_object", ["level"], unique=False
    )
    op.create_index(op.f("ix_gkgn_object_name"), "gkgn_object", ["name"], unique=False)
    op.create_index(
        op.f("ix_gkgn_object_region_id"), "gkgn_object", ["region_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gkgn_object_region_id"), table_name="gkgn_object")
    op.drop_index(op.f("ix_gkgn_object_name"), table_name="gkgn_object")
    op.drop_index(op.f("ix_gkgn_object_level"), table_name="gkgn_object")
    op.drop_index(op.f("ix_gkgn_object_gkgn_id"), table_name="gkgn_object")
    op.drop_index(op.f("ix_gkgn_object_district_id"), table_name="gkgn_object")
    op.drop_table("gkgn_object")
    op.drop_table("gkgn_type")
    # ### end Alembic commands ###
