"""empty message

Revision ID: 7df6e2728025
Revises: fa2056fa7d17
Create Date: 2019-11-13 17:47:53.426137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7df6e2728025'
down_revision = 'fa2056fa7d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp',
    sa.Column('gkgn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('oktmo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
