"""empty message

Revision ID: 7df6e2728025
Revises: fa2056fa7d17
Create Date: 2019-11-13 17:47:53.426137

"""

# revision identifiers, used by Alembic.
revision = "7df6e2728025"
down_revision = "fa2056fa7d17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
