"""add coord

Revision ID: 800980f971c4
Revises: bd1848dcb9b1
Create Date: 2019-11-12 15:28:33.389483

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "800980f971c4"
down_revision = "bd1848dcb9b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settlement", sa.Column("c_lat", sa.Float(precision=6), nullable=True)
    )
    op.add_column(
        "settlement", sa.Column("c_lon", sa.Float(precision=6), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settlement", "c_lon")
    op.drop_column("settlement", "c_lat")
    # ### end Alembic commands ###
