"""empty message

Revision ID: fa2056fa7d17
Revises: 800980f971c4
Create Date: 2019-11-13 15:36:20.037482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa2056fa7d17'
down_revision = '800980f971c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp')
    op.add_column('ATE', sa.Column('okato', sa.BigInteger(), nullable=True))
    op.add_column('ATE', sa.Column('okato_name', sa.String(length=256), nullable=True))
    op.add_column('ATE', sa.Column('oktmo', sa.BigInteger(), nullable=True))
    op.add_column('ATE', sa.Column('oktmo_name', sa.String(length=256), nullable=True))
    op.add_column('ATE', sa.Column('oktmo_up', sa.BigInteger(), nullable=True))
    op.add_column('settlement', sa.Column('okato', sa.BigInteger(), nullable=True))
    op.add_column('settlement', sa.Column('okato_name', sa.String(length=256), nullable=True))
    op.add_column('settlement', sa.Column('oktmo', sa.BigInteger(), nullable=True))
    op.add_column('settlement', sa.Column('oktmo_name', sa.String(length=256), nullable=True))
    op.add_column('settlement', sa.Column('oktmo_up', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlement', 'oktmo_up')
    op.drop_column('settlement', 'oktmo_name')
    op.drop_column('settlement', 'oktmo')
    op.drop_column('settlement', 'okato_name')
    op.drop_column('settlement', 'okato')
    op.drop_column('ATE', 'oktmo_up')
    op.drop_column('ATE', 'oktmo_name')
    op.drop_column('ATE', 'oktmo')
    op.drop_column('ATE', 'okato_name')
    op.drop_column('ATE', 'okato')
    op.create_table('tmp',
    sa.Column('gkgn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('oktmo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
